In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle
from pyECLAT import ECLAT

In [6]:
base_mercado1 = pd.read_csv("mercado.csv",header = None)
base_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

In [7]:
eclat = ECLAT(data = base_mercado1)

In [8]:
eclat.df_bin

   cerveja  arroz  pao  manteiga  cafe  feijao  leite
0        1      0    1         1     0       0      1
1        0      0    1         1     1       0      0
2        0      0    1         1     1       0      0
3        0      0    1         1     1       0      1
4        1      0    0         0     0       0      0
5        0      0    0         1     0       0      0
6        0      0    1         0     0       0      0
7        0      0    0         0     0       1      0
8        0      1    0         0     0       1      0
9        0      1    0         0     0       0      0

In [9]:
indices,suporte = eclat.fit(min_support=0.3,min_combination=1,max_combination=3)

Combination 1 by 1

3it [00:00, 249.33it/s]

Combination 2 by 2

3it [00:00, 285.18it/s]

Combination 3 by 3

1it [00:00, 181.38it/s]

In [10]:
indices

{'pao': [0, 1, 2, 3, 6],
 'manteiga': [0, 1, 2, 3, 5],
 'cafe': [1, 2, 3],
 'pao & manteiga': [0, 1, 2, 3],
 'pao & cafe': [1, 2, 3],
 'manteiga & cafe': [1, 2, 3],
 'pao & manteiga & cafe': [1, 2, 3]}

In [11]:
suporte

{'pao': 0.5,
 'manteiga': 0.5,
 'cafe': 0.3,
 'pao & manteiga': 0.4,
 'pao & cafe': 0.3,
 'manteiga & cafe': 0.3,
 'pao & manteiga & cafe': 0.3}