In [160]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle
import bs4 as bs
import urllib.request
import nltk
import spacy
import random
import string
import re

In [161]:
base_treinamento = pd.read_csv("tw_treinamento.csv",delimiter=";")
base_treinamento

,id,tweet_text,tweet_date,sentiment,query_used
0,1050785521201541121,@Laranjito76 A pessoa certa para isso seria o ...,Fri Oct 12 16:29:25 +0000 2018,1,:)
1,1050785431955140608,"@behin_d_curtain Para mim, é precisamente o co...",Fri Oct 12 16:29:04 +0000 2018,1,:)
2,1050785401248645120,Vou fazer um video hoje... estou pensando em f...,Fri Oct 12 16:28:56 +0000 2018,1,:)
3,1050785370982547461,"aaaaaaaa amei tanto essas polaroids, nem sei e...",Fri Oct 12 16:28:49 +0000 2018,1,:)
4,1050785368902131713,Valoriza o coração do menininho que vc tem. El...,Fri Oct 12 16:28:49 +0000 2018,1,:)
...,...,...,...,...,...
49995,1046762827053232128,:( é tão lindo que dói https://t.co/GqnpgyWWxB,Mon Oct 01 14:04:40 +0000 2018,0,:(
49996,1046762813362966529,"@veraluciarj Pois é.. tenho problema c/ ""coisa...",Mon Oct 01 14:04:37 +0000 2018,0,:(
49997,1046762806392082432,eu te amo tanto minja vidinha meu bem mais pre...,Mon Oct 01 14:04:35 +0000 2018,0,:(
49998,1046762752071618560,@itsLary @jessboluda Pfvor :(,Mon Oct 01 14:04:22 +0000 2018,0,:(
49999,1046762735340584962,@Renk_lol Passa ano Entra ano Eu nao desisto d...,Mon Oct 01 14:04:18 +0000 2018,0,:(

In [162]:
base_treinamento.drop(["id","tweet_date","query_used"],axis=1,inplace=True)

In [163]:
base_treinamento

                                              tweet_text  sentiment
0      @Laranjito76 A pessoa certa para isso seria o ...          1
1      @behin_d_curtain Para mim, é precisamente o co...          1
2      Vou fazer um video hoje... estou pensando em f...          1
3      aaaaaaaa amei tanto essas polaroids, nem sei e...          1
4      Valoriza o coração do menininho que vc tem. El...          1
...                                                  ...        ...
49995     :( é tão lindo que dói https://t.co/GqnpgyWWxB          0
49996  @veraluciarj Pois é.. tenho problema c/ "coisa...          0
49997  eu te amo tanto minja vidinha meu bem mais pre...          0
49998                      @itsLary @jessboluda Pfvor :(          0
49999  @Renk_lol Passa ano Entra ano Eu nao desisto d...          0

[50000 rows x 2 columns]

In [164]:
from spacy.lang.pt.stop_words import STOP_WORDS
stop_words = STOP_WORDS

In [165]:
pln = spacy.load("pt_core_news_sm")

In [166]:
def preprocessamento(texto):
    texto = texto.lower()
    
    texto = re.sub(r"@[A-Za-z0-9$-_@.&+]+"," ",texto)

    texto = re.sub(r"https?://[A-Za-z0-9./]+"," ",texto)

    texto = re.sub(r" +"," ",texto)

    lista_emocoes = {':)': 'emocaopositiva',
                   ':d': 'emocaopositiva',
                   ':(': 'emocaonegativa'}
    
    for emocoes in lista_emocoes:
        texto = texto.replace(emocoes,lista_emocoes[emocoes])

    documento = pln(texto)

    lista = []
    for token in documento:
        lista.append(token.lemma_)

    lista = [palavra for palavra in lista if palavra not in stop_words and palavra not in  string.punctuation]
    lista = " ".join([str(elemento) for elemento in lista if not elemento.isdigit()])

    return lista

In [167]:
base_treinamento["tweet_text"] = base_treinamento["tweet_text"].apply(preprocessamento)

In [168]:
base_treinamento_final = []

for texto,emocao in zip(base_treinamento["tweet_text"],base_treinamento["sentiment"]):
    if emocao == 1:
        dic = {"POSITIVO":True,"NEGATIVO":False}
    else:
        dic = {"POSITIVO":False,"NEGATIVO":True}

    base_treinamento_final.append([texto,dic.copy()])

In [169]:
len(base_treinamento_final)

50000

In [170]:
modelo = spacy.blank("pt")
textcat = modelo.add_pipe("textcat")
textcat.add_label("POSITIVO")
textcat.add_label("NEGATIVO")
historico = [ ]
from spacy.training import Example

In [171]:
modelo.begin_training()
for epoca in range(5):
    random.shuffle(base_treinamento_final)
    losses = {}
    for batch in spacy.util.minibatch(base_treinamento_final,512):
        textos = [modelo(texto) for texto,entities in batch]
        annotations = [{"cats":entities} for texto,entities in batch]
        examples = [Example.from_dict(doc, annotation) for doc, annotation in zip(
            textos, annotations
        )]
        modelo.update(examples, losses=losses)
        historico.append(losses)
    if epoca % 5 == 0:
        print(losses)

{'textcat': 1.7428134632652927}

In [172]:
historico_loss = []
for i in historico:
    historico_loss.append(i.get("textcat"))

In [173]:
historico_loss = np.array(historico_loss)
historico_loss

array([1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 1.74281346, 1.74281346,
       1.74281346, 1.74281346, 1.74281346, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.05820438, 0.05820438, 0.05820438, 0.05820438,
       0.05820438, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.01528663,
       0.01528663, 0.01528663, 0.01528663, 0.01528663, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00355693, 0.00355693, 0.00355693,
       0.00355693, 0.00355693, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682,
       0.00486682, 0.00486682, 0.00486682, 0.00486682, 0.00486682])

In [174]:
modelo.to_disk("modelo_tw")

In [175]:
modelo_carregado = spacy.load("modelo_tw")

In [176]:
base_dados_teste = pd.read_csv("tw_teste.csv",delimiter=";")
base_dados_teste

,id,tweet_text,tweet_date,sentiment,query_used
0,1029536486021099522,@Gazo1a Nossa! Muito obrigada :),Wed Aug 15 01:13:20 +0000 2018,1,:)
1,1029536496368406528,@BerzGamer vai pa puta que te pariu :),Wed Aug 15 01:13:23 +0000 2018,1,:)
2,1029536531655131137,QUER MAIS DESCONTOS? (14/08) ⭐⭐⭐⭐⭐ 🌐 Confira n...,Wed Aug 15 01:13:31 +0000 2018,1,:)
3,1029536560117678081,"EU VOU PEGAR VCS, ME AJUDEM GALERA, PELO AMOR ...",Wed Aug 15 01:13:38 +0000 2018,1,:)
4,1029536605852377088,Estávamos em casa do Zé e eu estava a morrer d...,Wed Aug 15 01:13:49 +0000 2018,1,:)
...,...,...,...,...,...
4995,1030528364145201153,@ol_cdanilo parece livro de autoajuda :(,Fri Aug 17 18:54:42 +0000 2018,0,:(
4996,1030528418235015168,@tatazoquita aaaaa sinto muito :((,Fri Aug 17 18:54:55 +0000 2018,0,:(
4997,1030528446122930176,To começando a sentir dor de novo e meu irmão ...,Fri Aug 17 18:55:02 +0000 2018,0,:(
4998,1030528453752352769,@ichbintw parece que no dia que toma a vacina ...,Fri Aug 17 18:55:04 +0000 2018,0,:(
4999,1030528465521586177,@nessagomesc @laymuniz23 poxaa acho q essa q v...,Fri Aug 17 18:55:07 +0000 2018,0,:(

In [177]:
base_dados_teste.drop(["id","tweet_date","query_used"],axis=1,inplace=True)

In [178]:
base_dados_teste

                                             tweet_text  sentiment
0                      @Gazo1a Nossa! Muito obrigada :)          1
1                @BerzGamer vai pa puta que te pariu :)          1
2     QUER MAIS DESCONTOS? (14/08) ⭐⭐⭐⭐⭐ 🌐 Confira n...          1
3     EU VOU PEGAR VCS, ME AJUDEM GALERA, PELO AMOR ...          1
4     Estávamos em casa do Zé e eu estava a morrer d...          1
...                                                 ...        ...
4995           @ol_cdanilo parece livro de autoajuda :(          0
4996                 @tatazoquita aaaaa sinto muito :((          0
4997  To começando a sentir dor de novo e meu irmão ...          0
4998  @ichbintw parece que no dia que toma a vacina ...          0
4999  @nessagomesc @laymuniz23 poxaa acho q essa q v...          0

[5000 rows x 2 columns]

In [179]:
base_dados_teste["tweet_text"] = base_dados_teste["tweet_text"].apply(preprocessamento)

In [180]:
previsoes_teste = []
for texto in base_dados_teste["tweet_text"]:
    previsao = modelo_carregado(texto)
    previsoes_teste.append(previsao.cats)

In [181]:
previsoes_teste

[{'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2517597269834368e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.1172818871236814e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.4132852754755731e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 4.0420164282295445e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1164279101194552e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.246607308137754e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.626841297929786e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.320348688859667e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.3746004867698502e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0185550536334631e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.4961513272737648e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.148002995587376e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.5484717152958183e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.980180782851676e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.827855507182903e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.439969517188729e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2517597269834368e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.126760361737979e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0373337033797725e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0437241826366517e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.191934431853952e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.442826195827365e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.2836437096884765e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.231611220959167e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.509908155929224e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.475355470072827e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.461113351477252e-08},
 {'POSITIVO': 0.9984299540519714, 'NEGATIVO': 0.0015700221993029118},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.413757099224313e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.863241377326631e-07},
 {'POSITIVO': 0.9999972581863403, 'NEGATIVO': 2.739462843237561e-06},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.166255453379563e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.762443405250451e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.679474999302329e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.220053012067183e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.0751510021455033e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.147469543473562e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.105573101602204e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.7501476529987485e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.36856139333031e-08},
 {'POSITIVO': 0.999998927116394, 'NEGATIVO': 1.0290004865964875e-06},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.034145142853049e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.4508518587681465e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.4544409054906282e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.072365911156339e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.167693224919276e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.7444719446757517e-07},
 {'POSITIVO': 0.9999995231628418, 'NEGATIVO': 4.657010492792324e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.018050141965432e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.467977455149594e-07},
 {'POSITIVO': 0.9999995231628418, 'NEGATIVO': 4.1745727230591e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.574394469296749e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 2.5606022191482225e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.002099687904774e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.749157428956096e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.858557893314355e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.9749585312165436e-07},
 {'POSITIVO': 0.9999961853027344, 'NEGATIVO': 3.7841987250430975e-06},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.075077424976371e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.6580719375269837e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.708164572595706e-07},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 5.548085368900502e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.541748203720999e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.557789878845142e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.516034041695093e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.3441466251151724e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.584188448257919e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.218399058368959e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.6579101586321485e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 1.8853351946290786e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.774836691647579e-08},
 {'POSITIVO': 0.9999957084655762, 'NEGATIVO': 4.329588591645006e-06},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.321884894878167e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.0465824469038125e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.84194745304012e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.212813316442407e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.355514869937906e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.5945676068440662e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.5060851410453324e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.549058432867241e-08},
 {'POSITIVO': 0.9999995231628418, 'NEGATIVO': 4.283632222268352e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 4.1427188079978805e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.5665288799482369e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.974677499878453e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.735058543152263e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.4528868064189737e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.036545295908581e-08},
 {'POSITIVO': 0.9999995231628418, 'NEGATIVO': 4.2174460190835816e-07},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 5.401793714554515e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.084728619905945e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.2150526863006235e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.9377559346576163e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.560918646731807e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.960359589745167e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.689218423616694e-08},
 {'POSITIVO': 0.9999954700469971, 'NEGATIVO': 4.5473320824385155e-06},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.6096975602740713e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.573897089381717e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.349292102138861e-08},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 6.454282583945314e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1539826516582252e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2469818955196388e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.696794527106249e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.02024979154703e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.5279886156349676e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.2708717867535597e-07},
 {'POSITIVO': 0.9999973773956299, 'NEGATIVO': 2.6300351692043478e-06},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.4494616468473396e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2517597269834368e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0373337033797725e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 2.994013073021051e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.384481020584644e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.971410992813617e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1413294487283565e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.2122966925053333e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.411638035937358e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.2164418567172106e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.7566054566486855e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.4593377051805874e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.006155964158097e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.458712924015344e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1408233291376746e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.405559117984012e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1719495773832023e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.919225535919395e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.304400094833909e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 1.1428417323600115e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.330489092462813e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.028669640225417e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.1062576510976214e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.256920990679646e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.781097449173103e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.5881541887429194e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.945567073060374e-08},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 6.494836952697369e-07},
 {'POSITIVO': 0.9999567270278931, 'NEGATIVO': 4.327192800701596e-05},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.0282595869502984e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1911443920098463e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.618764013590408e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0248397330769876e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.6948507663983037e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.8228341259791705e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.0459208371903514e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.13888640132609e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1014215317572962e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.3055146054248326e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1037748492981336e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2456044373720943e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.7826556586442166e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.239403755766034e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.363672693827539e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.0738107998095074e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.94320050342867e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.113946149824187e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0529440430673276e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.957101230549597e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.522777885540563e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.043820212018545e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1729748905509041e-07},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 5.71593091081013e-07},
 {'POSITIVO': 0.9994983673095703, 'NEGATIVO': 0.0005016687209717929},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.21609173631532e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.436715776520941e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.575431647590449e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 1.5537830577727618e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 1.8990151318121207e-07},
 {'POSITIVO': 0.9999995231628418, 'NEGATIVO': 4.7530346591884154e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.181856804232666e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.743942376237101e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.574116432986557e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.4739906595859793e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.923145682932955e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.6582079354066082e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.487372334300744e-08},
 {'POSITIVO': 0.9999985694885254, 'NEGATIVO': 1.3740042277277098e-06},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.760096482594236e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.2903526541995234e-07},
 {'POSITIVO': 0.9999995231628418, 'NEGATIVO': 4.6034656975280086e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.748399398593392e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.692000446648308e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.3819238492706063e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0055966015443119e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.848213682682399e-07},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 5.984500148770167e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2365747181775077e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.576422879016718e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 4.02721042291887e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.806167363038185e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2649024938582443e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.4841359075035143e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.955877130896624e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.05565179007317e-08},
 {'POSITIVO': 0.9999485015869141, 'NEGATIVO': 5.153461825102568e-05},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.751940542111697e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.104469760093707e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.037494332782444e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.312881749981898e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.387817292197724e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.988255770082105e-08},
 {'POSITIVO': 0.9999990463256836, 'NEGATIVO': 9.622701782063814e-07},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 6.376642431860091e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.137074931051757e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.043389788601417e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 2.984508853387524e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.9368251236737706e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0967738006684158e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2517597269834368e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.362844935850262e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.223392455875e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.050899597516036e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.885152549150007e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0271587314036879e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 2.1369794822589938e-08},
 {'POSITIVO': 0.9999986886978149, 'NEGATIVO': 1.2873512105215923e-06},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.588343702176644e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.708164572595706e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.808132120752816e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.666552275826689e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.575245237172567e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.050899597516036e-08},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 6.140070354376803e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0259545035751216e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.291694004152305e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 1.927337223150971e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.456706268589187e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.615493090412201e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.432806749970041e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2102991320261935e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.88240316246447e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2517597269834368e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.7527304758432365e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.792837901528401e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.839083362322526e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 1.8276851676546357e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1005962363697108e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.140829273386771e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.23394313947756e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.9610139879187045e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.6131113511619333e-07},
 {'POSITIVO': 0.9999994039535522, 'NEGATIVO': 6.546800364048977e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.2246239811684063e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0127087790579026e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1165387547862338e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.6920602042300743e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.905724727497727e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.809951879129585e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 2.5606022191482225e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.595886374161637e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.854888674936774e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.806608775557834e-08},
 {'POSITIVO': 0.9999988079071045, 'NEGATIVO': 1.2050983286826522e-06},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.170912314473753e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.793703732910217e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 2.5073187970292565e-08},
 {'POSITIVO': 0.973605215549469, 'NEGATIVO': 0.02639482170343399},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.975008031735342e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.182480898227368e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1549834511015433e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.7217131187408086e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.2517597269834368e-07},
 {'POSITIVO': 0.9999995231628418, 'NEGATIVO': 4.4828377099292993e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.630263437225949e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.6351570277875e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.109543117967405e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.103523020328794e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 4.557789878845142e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.2453032139965217e-08},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.342574359521677e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.815822881530039e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 6.36989625490969e-08},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.387772551377566e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.412882834818447e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.524249739759398e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.3698250945235486e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.572681681722315e-08},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.443899234094715e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 7.74705952721888e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0373337033797725e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.0852317912131184e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.031838010590036e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.8254221124134347e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.3481006533311302e-07},
 {'POSITIVO': 0.9999955892562866, 'NEGATIVO': 4.379270649224054e-06},
 {'POSITIVO': 0.9999992847442627, 'NEGATIVO': 7.49019704926468e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 5.92189017822875e-08},
 {'POSITIVO': 0.9999914169311523, 'NEGATIVO': 8.535805136489216e-06},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 8.602981438343704e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.810737111592971e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.5832029021112248e-07},
 {'POSITIVO': 0.9999997615814209, 'NEGATIVO': 2.2585973624700273e-07},
 {'POSITIVO': 1.0, 'NEGATIVO': 3.357205713427902e-08},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.0805713657191518e-07},
 {'POSITIVO': 0.9999996423721313, 'NEGATIVO': 3.0692527275277826e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 1.1489925810792556e-07},
 {'POSITIVO': 0.9999998807907104, 'NEGATIVO': 9.266729250612116e-08},

In [182]:
previsao_final = []
for previsao in previsoes_teste:
    if previsao["POSITIVO"] > previsao["NEGATIVO"]:
        previsao_final.append(1)
    else:
        previsao_final.append(0)

previsao_final = np.array(previsao_final)

In [183]:
respostas_reais = base_dados_teste["sentiment"].values

In [184]:
respostas_reais

array([1, 1, 1, ..., 0, 0, 0])

In [185]:
previsao_final

array([1, 1, 1, ..., 0, 0, 0])

In [186]:
from sklearn.metrics import accuracy_score
accuracy_score(respostas_reais,previsao_final)

0.9976